### ISSUE TITLE
unable to install 1.0.0a1

### ISSUE THREAD

**Issue by lemmy04** [ansible/ansible-builder#204]
I'm following the installation instructions, but it fails:

```
mathias@appsrv:~$ sudo pip3 install https://github.com/ansible/ansible-builder/archive/1.0.0a1.zip
Collecting https://github.com/ansible/ansible-builder/archive/1.0.0a1.zip
  Downloading https://github.com/ansible/ansible-builder/archive/1.0.0a1.zip
     / 204kB 8.4MB/s
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-req-build-z5ycqunp/.eggs/pbr-5.5.1-py3.7.egg/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-req-build-z5ycqunp/.eggs/pbr-5.5.1-py3.7.egg/pbr/util.py", line 271, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-req-build-z5ycqunp/.eggs/pbr-5.5.1-py3.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-req-build-z5ycqunp/.eggs/pbr-5.5.1-py3.7.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-req-build-z5ycqunp/.eggs/pbr-5.5.1-py3.7.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-req-build-z5ycqunp/.eggs/pbr-5.5.1-py3.7.egg/pbr/packaging.py", line 880, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name ansible-builder was given, but was not able to be found.
    error in setup command: Error parsing /tmp/pip-req-build-z5ycqunp/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name ansible-builder was given, but was not able to be found.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-z5ycqunp/

```

The last version that is installable with "pip3 install ansible-builder" is 0.6.0.
Any ideas?

**Comment by shanemcd** [comment]
Weird. Can you try:

```
pip install ansible-builder==1.0.0.0a1
```

**Comment by lemmy04** [comment]
that worked... but a pip install without the version installs 0.6.0.

**Comment by AlanCoding** [comment]
That makes sense, but this should be resolved in time when the alpha releases become non-alpha.
