### ISSUE TITLE
execution_environments.yml missing "dependencies" section makes ansible-builder build throw traceback

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-builder#26]
should fail and tell me nicely that my execution_environment.yml is missing the "dependencies" section

**Comment by kdelee** [comment]
@shanemcd ran into this while demoing current state of things
@beeankha may be of interest

**Comment by AlanCoding** [comment]
The tests make heavy use of empty specs.

https://github.com/ansible/ansible-builder/blob/31d565303b3e29de835340e75e486467eb467320/test/test_main.py#L53

It makes a Containerfile with just the base image right? I feel like it's too early to be mucking with this.

However, it occurred to me that we should warn if the user provides keys that _are not_ used, because that's more likely to be a valid complaint, and would probably solve the same issue you had. I don't think any human would make an empty spec file and expect an error message. I _do_ think humans will guess what keys to put in, get it wrong, and have that interpreted by the program as an empty spec.

_and when I say "spec" I should probably say "definition"_

**Comment by kdelee** [comment]
this is what I'm showing: if you touch an empty file `execution-environment.yml` you can reproduce

Guess its doing a raw `get` on the `galaxy` subdict of `dependencies` 

```
$ touch execution-environment.yml
$ ansible-builder create
Traceback (most recent call last):
  File "/home/elijah/.cache/pypoetry/virtualenvs/ansible-builder-d47oRQeY-py3.8/bin/ansible-builder", line 11, in <module>
    load_entry_point('ansible-builder', 'console_scripts', 'ansible-builder')()
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/cli.py", line 77, in run
    ab = prepare()
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/cli.py", line 73, in prepare
    return AnsibleBuilder(**vars(args))
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/main.py", line 23, in __init__
    self.containerfile = Containerfile(
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/main.py", line 100, in __init__
    self.build_steps()
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/main.py", line 106, in build_steps
    [self.steps.append(step) for step in GalaxySteps(containerfile=self)]
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/main.py", line 124, in __new__
    if not definition.galaxy_requirements_file:
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/main.py", line 80, in galaxy_requirements_file
    galaxy_file = self.raw.get('dependencies', {}).get('galaxy')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by beeankha** [comment]
PR https://github.com/ansible/ansible-builder/pull/38 has a fix for this issue included, and it has been merged!

**Comment by kdelee** [comment]
works for me, 

```
 touch execution-environment.yml 
ansible-builder build
Writing partial Containerfile without collection requirements
Running command:
  podman build -f context/Containerfile -t ansible-execution-env:latest context
STEP 1: FROM shanemcd/ansible-runner
STEP 2: ADD introspect.py /usr/local/bin/introspect
--> dee6986c482
STEP 3: RUN chmod +x /usr/local/bin/introspect
STEP 4: COMMIT ansible-execution-env:latest
--> 36967012640
36967012640bc379fbd576018a1f0698899ad661f24dec2948d4140cefdc52ba
Running command:
  podman run --rm ansible-execution-env:latest introspect
python: []
system: []

Rewriting Containerfile to capture collection requirements
Running command:
  podman build -f context/Containerfile -t ansible-execution-env:latest context
STEP 1: FROM shanemcd/ansible-runner
STEP 2: ADD introspect.py /usr/local/bin/introspect
--> Using cache dee6986c4827bb33d6ec16fe46233105759815380f9cfd9b96e26dc8fef1b952
STEP 3: RUN chmod +x /usr/local/bin/introspect
--> Using cache 36967012640bc379fbd576018a1f0698899ad661f24dec2948d4140cefdc52ba
STEP 4: ADD requirements.txt /build/
--> 7e5f14f38cd
STEP 5: RUN pip3 install --upgrade -r /build/requirements.txt
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
You must give at least one requirement to install (see "pip help install")
STEP 6: COMMIT ansible-execution-env:latest
--> d07f798df8b
d07f798df8bb0916225f28caaecb3ba162c094cf1b1f9000e5e84759df3f9969
Complete! The build context can be found at: context
```

we can work on adding coverage for this in the integration tests later
