### ISSUE TITLE
Test compatibility with ansible-test

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#37]
I've collected an example with `community.aws`

```
ERROR: tests/unit/compat/mock.py:101:12: import-outside-toplevel: Import outside toplevel (_io)
See documentation for help: https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/pylint.html
Running sanity test 'replace-urlopen' with Python 3.7
Running sanity test 'rstcheck' with Python 3.7
Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/awx_collection/bin/ansible-test", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/alancoding/Documents/repos/ansible/bin/ansible-test", line 28, in <module>
    main()
  File "/Users/alancoding/Documents/repos/ansible/bin/ansible-test", line 24, in main
    cli_main()
  File "/Users/alancoding/Documents/repos/ansible/test/lib/ansible_test/_internal/cli.py", line 173, in main
    args.func(config)
  File "/Users/alancoding/Documents/repos/ansible/test/lib/ansible_test/_internal/sanity/__init__.py", line 191, in command_sanity
    result = test.test(args, sanity_targets, version)
  File "/Users/alancoding/Documents/repos/ansible/test/lib/ansible_test/_internal/sanity/rstcheck.py", line 80, in test
    results = parse_to_list_of_dict(pattern, stderr)
  File "/Users/alancoding/Documents/repos/ansible/test/lib/ansible_test/_internal/util.py", line 712, in parse_to_list_of_dict
    raise Exception('Pattern "%s" did not match values:\n%s' % (pattern, '\n'.join(unmatched)))
Exception: Pattern "^(?P<path>[^:]*):(?P<line>[0-9]+): \((?P<level>INFO|WARNING|ERROR|SEVERE)/[0-4]\) (?P<message>.*)$" did not match values:
/Users/alancoding/.virtualenvs/awx_collection/bin/python: No module named rstcheck
```

(was resolved locally with `pip install rstcheck`)

This was after installing and running `ansible-test sanity`. The CLI `ansible-test` allows running inside of docker. We should produce an EE for `community.aws`, feed it into `ansible-test`, and verify that it does not fail on missing `rstcheck`.

**Comment by AlanCoding** [comment]
For whatever reason, I'm not able to replicate this with the default Ansible container image for test

https://github.com/ansible/default-test-container

**Comment by AlanCoding** [comment]
so, rstcheck is only a test utility, and it's been established that ansible-test does _not_ validate presence of dependencies.
