### ISSUE TITLE
WORKDIR issue during build

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-builder#501]
Reproducer:

```yaml
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest
options:
  package_manager_path: /usr/bin/microdnf
  workdir: /myworkdir
dependencies:
  python_interpreter:
    package_system: python39
    python_path: /usr/bin/python3.9
  ansible_core:
    package_pip: ansible==7.0.0
  ansible_runner:
    package_pip: ansible-runner==2.2.1   # install from PyPI
  python:
    - psutil
    - pyvmomi
  galaxy: |
    collections:
    - community.vmware
```

Error:

```pytb
Expected requirements file not present at: /runner/requirements.txt
Traceback (most recent call last):
  File "/output/scripts/introspect.py", line 401, in <module>
    main()
  File "/output/scripts/introspect.py", line 394, in main
    run_introspect(args, logger)
  File "/output/scripts/introspect.py", line 232, in run_introspect
    data = process(args.folder, user_pip=args.user_pip, user_bindep=args.user_bindep)
  File "/output/scripts/introspect.py", line 113, in process
    col_pip_lines = pip_file_data(user_pip)
  File "/output/scripts/introspect.py", line 29, in pip_file_data
    pip_content = read_req_file(path)
  File "/output/scripts/introspect.py", line 24, in read_req_file
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
Error: building at STEP "RUN $PYCMD /output/scripts/introspect.py introspect --sanitize --user-pip=requirements.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt": while running runtime: exit status 1
```

**Comment by nitzmahone** [comment]
PS, until #512 has merged and released, including `--squash off` on the `ansible-builder build` CLI invocation should work around the issue. It appears to be a nasty `podman build` bug that only manifests when squashing is enabled, an ephemeral build stage has inherited its `WORKDIR` from a parent image, and a `COPY` directive is using a relative destination path (which is supposed to use `WORKDIR` as the base), and (some other condition that is present in our supported EE images that is not in a vanilla image). In that case, the `COPY` succeeds, but seems to go into the ether (a `find` can't find the target file anywhere in the image, even though `RUN pwd` provides the correct value). Could've been worse- in the same case, if an *absolute* destination path is used, `podman` will just segfault :laughing:
