### ISSUE TITLE
Catch errors from parsing collection python requirements

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#63]
Example:

```
$ ansible-builder introspect --sanitize ~/Documents/repos/collection-dependencies-demo/target/
Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 10), (line:1, col:11)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'in confi'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alancoding/.virtualenvs/ansible-builder/bin/ansible-builder", line 33, in <module>
    sys.exit(load_entry_point('ansible-builder', 'console_scripts', 'ansible-builder')())
  File "/Users/alancoding/Documents/repos/ansible-builder/ansible_builder/cli.py", line 30, in run
    data['python'] = sanitize_requirements(data['python'])
  File "/Users/alancoding/Documents/repos/ansible-builder/ansible_builder/requirements.py", line 23, in sanitize_requirements
    for req in parsed:
  File "/Users/alancoding/Documents/repos/requirements-parser/requirements/parser.py", line 50, in parse
    yield Requirement.parse(line)
  File "/Users/alancoding/Documents/repos/requirements-parser/requirements/requirement.py", line 239, in parse
    return cls.parse_line(line)
  File "/Users/alancoding/Documents/repos/requirements-parser/requirements/requirement.py", line 217, in parse_line
    pkg_req = Req.parse(line)
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3155, in parse
    req, = parse_requirements(s)
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in parse_requirements
    yield Requirement(line)
  File "/Users/alancoding/.virtualenvs/ansible-builder/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'in confi'"
```

The root cause of this traceback is that a collection has a `requirements.txt` file which is not formatted correctly. We should never error with a traceback like this, this also doesn't give any actionable information (not clear _which_ collection had the bad requirements).

This may be subject to discussion, but my proposal would be:

 - do not halt execution in this case, but instead, ignore the bad requirements file
 - issue a warning to the console, giving the bad requirements file and the name of the collection involved

In practice, this should be uncommon, so there is not particular urgency for solving this.

**Comment by AlanCoding** [comment]
being addressed in #59
